#ifndef PORT_CFG_H
#define PORT_CFG_H

//function like macro stringification
/*example :
 *
 * #define print(x)  printf(#x)
 * ---> print(ehab)--->printf("ehab")
 * */


/*concatination*/
/*
 * #define CONC(x,y)   x##y
 *
 * ---> xy
 *
 * */


/*Configure the MCU Pins direction, options :  1- INPUT
											   2- OUTPUT		*/
#define PORTA_PIN7_DIR   OUTPUT
#define PORTA_PIN6_DIR   OUTPUT
#define PORTA_PIN5_DIR   OUTPUT
#define PORTA_PIN4_DIR   OUTPUT
#define PORTA_PIN3_DIR   OUTPUT
#define PORTA_PIN2_DIR   OUTPUT
#define PORTA_PIN1_DIR   OUTPUT
#define PORTA_PIN0_DIR   OUTPUT

#define PORTB_PIN7_DIR   OUTPUT
#define PORTB_PIN6_DIR   INPUT
#define PORTB_PIN5_DIR   INPUT
#define PORTB_PIN4_DIR   INPUT
#define PORTB_PIN3_DIR   INPUT
#define PORTB_PIN2_DIR   INPUT
#define PORTB_PIN1_DIR   INPUT
#define PORTB_PIN0_DIR   INPUT

#define PORTC_PIN7_DIR   INPUT
#define PORTC_PIN6_DIR   INPUT
#define PORTC_PIN5_DIR   INPUT
#define PORTC_PIN4_DIR   INPUT
#define PORTC_PIN3_DIR   INPUT
#define PORTC_PIN2_DIR   INPUT
#define PORTC_PIN1_DIR   INPUT
#define PORTC_PIN0_DIR   INPUT

#define PORTD_PIN7_DIR   INPUT
#define PORTD_PIN6_DIR   INPUT
#define PORTD_PIN5_DIR   INPUT
#define PORTD_PIN4_DIR   INPUT
#define PORTD_PIN3_DIR   INPUT
#define PORTD_PIN2_DIR   INPUT
#define PORTD_PIN1_DIR   INPUT
#define PORTD_PIN0_DIR   INPUT


/*Configure Initial value of pins    in case of INPUT direction   	1-FLOATING
 * 																	2-PULLED_UP
 *
 * 									in case of OUTPUT direction		1-HIGH
 * 																	2-LOW
 * */

#define PORTA_PIN7_INIT_VAL  FLOATING
#define PORTA_PIN6_INIT_VAL  FLOATING
#define PORTA_PIN5_INIT_VAL  FLOATING
#define PORTA_PIN4_INIT_VAL  FLOATING
#define PORTA_PIN3_INIT_VAL  FLOATING
#define PORTA_PIN2_INIT_VAL  FLOATING
#define PORTA_PIN1_INIT_VAL  FLOATING
#define PORTA_PIN0_INIT_VAL  FLOATING

#define PORTB_PIN7_INIT_VAL  FLOATING
#define PORTB_PIN6_INIT_VAL  FLOATING
#define PORTB_PIN5_INIT_VAL  FLOATING
#define PORTB_PIN4_INIT_VAL  FLOATING
#define PORTB_PIN3_INIT_VAL  FLOATING
#define PORTB_PIN2_INIT_VAL  FLOATING
#define PORTB_PIN1_INIT_VAL  FLOATING
#define PORTB_PIN0_INIT_VAL  FLOATING

#define PORTC_PIN7_INIT_VAL  FLOATING
#define PORTC_PIN6_INIT_VAL  FLOATING
#define PORTC_PIN5_INIT_VAL  FLOATING
#define PORTC_PIN4_INIT_VAL  FLOATING
#define PORTC_PIN3_INIT_VAL  FLOATING
#define PORTC_PIN2_INIT_VAL  FLOATING
#define PORTC_PIN1_INIT_VAL  FLOATING
#define PORTC_PIN0_INIT_VAL  FLOATING

#define PORTD_PIN7_INIT_VAL  FLOATING
#define PORTD_PIN6_INIT_VAL  FLOATING
#define PORTD_PIN5_INIT_VAL  FLOATING
#define PORTD_PIN4_INIT_VAL  FLOATING
#define PORTD_PIN3_INIT_VAL  FLOATING
#define PORTD_PIN2_INIT_VAL  FLOATING
#define PORTD_PIN1_INIT_VAL  FLOATING
#define PORTD_PIN0_INIT_VAL  FLOATING








#endif /*PORT_CFG_H*/
